"""Initial schema

Revision ID: 5824ca053113
Revises: 
Create Date: 2025-06-23 18:07:56.591601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5824ca053113'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_posts', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('job_posts', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('job_posts', 'company',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('job_posts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('job_posts', 'hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(op.f('job_posts_hash_key'), 'job_posts', type_='unique')
    op.create_index(op.f('ix_job_posts_category'), 'job_posts', ['category'], unique=False)
    op.create_index(op.f('ix_job_posts_hash'), 'job_posts', ['hash'], unique=True)
    op.create_index(op.f('ix_job_posts_location'), 'job_posts', ['location'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_posts_location'), table_name='job_posts')
    op.drop_index(op.f('ix_job_posts_hash'), table_name='job_posts')
    op.drop_index(op.f('ix_job_posts_category'), table_name='job_posts')
    op.create_unique_constraint(op.f('job_posts_hash_key'), 'job_posts', ['hash'], postgresql_nulls_not_distinct=False)
    op.alter_column('job_posts', 'hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('job_posts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('job_posts', 'company',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('job_posts', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('job_posts', 'updated_at')
    # ### end Alembic commands ###
