"""Add salary fields to JobPost

Revision ID: c5b049eea17b
Revises: c5f92cd2575b
Create Date: 2025-06-24 16:12:16.148697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5b049eea17b'
down_revision: Union[str, None] = 'c5f92cd2575b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
