"""Add salary fields

Revision ID: c5f92cd2575b
Revises: 5824ca053113
Create Date: 2025-06-24 14:52:30.787174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5f92cd2575b'
down_revision: Union[str, None] = '5824ca053113'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_posts', sa.Column('salary_min', sa.Float(), nullable=True))
    op.add_column('job_posts', sa.Column('salary_max', sa.Float(), nullable=True))
    op.add_column('job_posts', sa.Column('salary_currency', sa.String(), nullable=True))
    op.add_column('job_posts', sa.Column('salary_num', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_posts', 'salary_num')
    op.drop_column('job_posts', 'salary_currency')
    op.drop_column('job_posts', 'salary_max')
    op.drop_column('job_posts', 'salary_min')
    # ### end Alembic commands ###
